name: Windows C++ Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Compile with g++
        run: |
          g++ -std=c++17 -Wall -Wextra WinMain.cpp Generals/Code/Main/*.cpp -o generals.exe
