name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Build with MSBuild
      run: |
        msbuild Generals/Code/Main/YourProject.dsp `
          /p:Configuration=Release `
          /p:Platform="Win32" `
          /t:Build `
          /m `
          /clp:ErrorsOnly;Summary

    - name: Run static analysis
      run: |
        msbuild Generals/Code/Main/YourProject.dsp `
          /t:Build `
          /p:RunCodeAnalysis=true `
          /p:CodeAnalysisRuleSet=AllRules

    - name: Run tests (if available)
      run: |
        if exist ".\bin\Release\YourExecutable.exe" (
          .\bin\Release\YourExecutable.exe --test
        )
