name: Windows C++ Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up MinGW (G++)
        uses: egor-tensin/setup-mingw@v2
        with:
          version: 12.2.0
          platform: x64

      - name: Compile with g++
        run: |
          g++ -std=c++17 -Wall -Wextra ^
            WinMain.cpp ^
            Generals/Code/Main/*.cpp ^
            -o generals.exe
