name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    # ✅ Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # ✅ Setup MSBuild for Visual Studio
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    # ✅ Compile in Release mode, treat warnings as errors, add new include path
    - name: Build with MSBuild
      run: |
        msbuild Generals/Code/Main/YourProject.sln `
          /p:Configuration=Release `
          /p:Platform="Win32" `
          /p:TreatWarningsAsErrors=true `
          /p:AdditionalIncludeDirectories="GeneralsMD/Code/GameEngine/Source/GameClient" `
          /m `
          /clp:ErrorsOnly;Summary
      shell: pwsh

    # ✅ Run Static Analysis (optional but recommended)
    - name: Run static analysis
      run: |
        msbuild Generals/Code/Main/YourProject.sln `
          /p:RunCodeAnalysis=true `
          /p:CodeAnalysisRuleSet="AllRules.ruleset" `
          /p:AdditionalIncludeDirectories="GeneralsMD/Code/GameEngine/Source/GameClient"
      shell: pwsh

    # ✅ Run tests (only if the compiled executable exists)
    - name: Run tests
      run: |
        if (Test-Path ".\bin\Release\YourExecutable.exe") {
          .\bin\Release\YourExecutable.exe --test
        } else {
          Write-Host "No tests found or build failed."
        }
      shell: pwsh
